### ISSUE TITLE
外部ファイルで設定

### ISSUE THREAD

**Issue by rokoucha** [Chikuwabu/Kanity#15]
- ウィンドウサイズとか
- 読み込むスクリプトの設定とか
- タイトル設定とか

**Comment by otya128** [comment]
フォーマットを何にするか

**Comment by rokoucha** [comment]
いじられると困るのでバイナリーとかにしたみ

**Comment by tosuke** [comment]
config操作のソフトを作るのか

**Comment by otya128** [comment]
std.jsonとかDから扱いやすい奴がいい

**Comment by tosuke** [comment]
対応しました
起動するスクリプトはまだ実装してない

**Comment by tosuke** [comment]
6ea1e97e8641a3bd51d12aa8c825e9655af2e73a
対応しました
